from pathlib import Path

path = Path('app/src/main/java/se/familjekalender/app/ExactCalendarScreen.kt')
text = path.read_text()

if 'Denna och framåt' in text and 'candidate.seriesId == event.seriesId' in text and 'val futureSeries =' in text:
    print('Series delete scopes already applied')
    raise SystemExit(0)

old = '''    deleteChoiceEvent?.let { event ->\n        val today = LocalDate.now()\n        val series = allEvents.filter { candidate ->\n            candidate.source != "sportadmin" &&\n                candidate.memberId == event.memberId &&\n                candidate.title == event.title &&\n                !candidate.date.isBefore(today)\n        }.sortedWith(compareBy<SyncEvent> { it.date }.thenBy { it.time })\n\n        AlertDialog(\n            onDismissRequest = { deleteChoiceEvent = null },\n            title = { Text("Ta bort aktivitet") },\n            text = {\n                Text(\n                    if (series.size > 1)\n                        "Ta bort bara denna förekomst eller hela den återkommande serien (${series.size} framtida aktiviteter)?"\n                    else\n                        "Ta bort denna aktivitet?"\n                )\n            },\n            confirmButton = {\n                Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {\n                    if (series.size > 1) {\n                        TextButton(onClick = {\n                            onDeleteMany(series)\n                            deleteChoiceEvent = null\n                        }) { Text("Hela serien", color = MaterialTheme.colorScheme.error) }\n                    }\n                    Button(onClick = {\n                        onDelete(event)\n                        deleteChoiceEvent = null\n                    }) { Text("Bara denna") }\n                }\n            },\n            dismissButton = { TextButton(onClick = { deleteChoiceEvent = null }) { Text("Avbryt") } }\n        )\n    }\n'''

new = '''    deleteChoiceEvent?.let { event ->\n        val series = allEvents.filter { candidate ->\n            candidate.source != "sportadmin" &&\n                if (event.seriesId != null) {\n                    candidate.seriesId == event.seriesId\n                } else {\n                    candidate.seriesId == null &&\n                        candidate.source == event.source &&\n                        candidate.memberId == event.memberId &&\n                        candidate.title == event.title &&\n                        candidate.time == event.time &&\n                        candidate.endTime == event.endTime\n                }\n        }.sortedWith(compareBy<SyncEvent> { it.date }.thenBy { it.time })\n        val futureSeries = series.filter { candidate ->\n            candidate.date.isAfter(event.date) ||\n                (candidate.date == event.date && candidate.time >= event.time)\n        }\n\n        AlertDialog(\n            onDismissRequest = { deleteChoiceEvent = null },\n            title = { Text("Ta bort aktivitet") },\n            text = {\n                Text(\n                    if (series.size > 1)\n                        "Välj om bara denna förekomst, denna och framåt eller hela serien ska tas bort."\n                    else\n                        "Ta bort denna aktivitet?"\n                )\n            },\n            confirmButton = {\n                Column(horizontalAlignment = Alignment.End) {\n                    if (series.size > 1) {\n                        TextButton(onClick = {\n                            onDeleteMany(series)\n                            deleteChoiceEvent = null\n                        }) { Text("Hela serien", color = MaterialTheme.colorScheme.error) }\n                        TextButton(onClick = {\n                            onDeleteMany(futureSeries)\n                            deleteChoiceEvent = null\n                        }) { Text("Denna och framåt", color = MaterialTheme.colorScheme.error) }\n                    }\n                    Button(onClick = {\n                        onDelete(event)\n                        deleteChoiceEvent = null\n                    }) { Text("Bara denna") }\n                }\n            },\n            dismissButton = { TextButton(onClick = { deleteChoiceEvent = null }) { Text("Avbryt") } }\n        )\n    }\n'''

if old not in text:
    raise SystemExit('Series delete dialog anchor not found')

path.write_text(text.replace(old, new, 1))
print('Precise series delete scopes applied')
