from pathlib import Path

# Work rotation: one stable series id per saved rotation.
exact = Path('app/src/main/java/se/familjekalender/app/ExactCalendarScreen.kt')
text = exact.read_text()
old = '''                    scope.launch {\n                        runCatching {\n                            repeat(52) { weekIndex ->\n                                val template = weeks[weekIndex % rotationWeeks]\n                                val monday = startDate.plusWeeks(weekIndex.toLong())\n                                template.weekdays.sorted().forEach { day ->\n                                    val date = monday.plusDays((day - 1).toLong())\n                                    val times = template.dayTimes[day] ?: (template.startTime to template.endTime)\n                                    val eventTitle = \"Jobb · ${times.first}–${times.second}\"\n                                    SupabaseSync.addEvent(activeSession, eventTitle, date, times.first, times.second, selectedMemberId)\n                                }\n                            }\n                        }.onSuccess { onChanged() }\n'''
new = '''                    scope.launch {\n                        runCatching {\n                            val seriesId = java.util.UUID.randomUUID().toString()\n                            repeat(52) { weekIndex ->\n                                val template = weeks[weekIndex % rotationWeeks]\n                                val monday = startDate.plusWeeks(weekIndex.toLong())\n                                template.weekdays.sorted().forEach { day ->\n                                    val date = monday.plusDays((day - 1).toLong())\n                                    val times = template.dayTimes[day] ?: (template.startTime to template.endTime)\n                                    val eventTitle = \"Jobb · ${times.first}–${times.second}\"\n                                    SupabaseSync.addEvent(activeSession, eventTitle, date, times.first, times.second, selectedMemberId, seriesId)\n                                }\n                            }\n                        }.onSuccess { onChanged() }\n'''
if old not in text:
    raise SystemExit('Work rotation anchor not found')
text = text.replace(old, new, 1)
exact.write_text(text)

# School/daycare schedule: one stable series id per saved schedule.
school = Path('app/src/main/java/se/familjekalender/app/SchoolScheduleDialog.kt')
text = school.read_text()
old = '''                    scope.launch {\n                        runCatching {\n                            repeat(52) { weekIndex ->\n                                val template = weeks[weekIndex % rotationWeeks]\n                                val monday = startDate.plusWeeks(weekIndex.toLong())\n                                template.weekdays.sorted().forEach { day ->\n                                    val date = monday.plusDays((day - 1).toLong())\n                                    val times = template.dayTimes[day] ?: (\"07:30\" to \"16:00\")\n                                    SupabaseSync.addEvent(\n                                        activeSession,\n                                        \"$type · ${times.first}–${times.second}\",\n                                        date,\n                                        times.first,\n                                        times.second,\n                                        selectedMemberId\n                                    )\n                                }\n                            }\n                        }.onSuccess { onChanged() }\n'''
new = '''                    scope.launch {\n                        runCatching {\n                            val seriesId = java.util.UUID.randomUUID().toString()\n                            repeat(52) { weekIndex ->\n                                val template = weeks[weekIndex % rotationWeeks]\n                                val monday = startDate.plusWeeks(weekIndex.toLong())\n                                template.weekdays.sorted().forEach { day ->\n                                    val date = monday.plusDays((day - 1).toLong())\n                                    val times = template.dayTimes[day] ?: (\"07:30\" to \"16:00\")\n                                    SupabaseSync.addEvent(\n                                        activeSession,\n                                        \"$type · ${times.first}–${times.second}\",\n                                        date,\n                                        times.first,\n                                        times.second,\n                                        selectedMemberId,\n                                        seriesId\n                                    )\n                                }\n                            }\n                        }.onSuccess { onChanged() }\n'''
if old not in text:
    raise SystemExit('School schedule anchor not found')
text = text.replace(old, new, 1)
school.write_text(text)

print('Stable series IDs applied to work rotation and school/daycare schedules')
