package se.familjekalender.app

import java.util.Locale

data class RecipeIngredient(
    val amount: String,
    val name: String,
)

data class FamilyRecipe(
    val id: String,
    val title: String,
    val category: String,
    val description: String,
    val servings: Int,
    val timeMinutes: Int,
    val ingredients: List<RecipeIngredient>,
    val steps: List<String>,
    val tags: List<String> = emptyList(),
)

object FamilyRecipeCatalog {
    val all: List<FamilyRecipe> =
        listOf(
            FamilyRecipe(
                id = "pannkakor",
                title = "Pannkakor",
                category = "Frukost & enkelt",
                description = "Klassiska tunna pannkakor med mjuk mitt och lätt frasiga kanter.",
                servings = 4,
                timeMinutes = 30,
                ingredients = listOf(
                    RecipeIngredient("2,5 dl", "vetemjöl"),
                    RecipeIngredient("6 dl", "mjölk"),
                    RecipeIngredient("3", "ägg"),
                    RecipeIngredient("0,5 tsk", "salt"),
                    RecipeIngredient("2 msk", "smör"),
                ),
                steps = listOf(
                    "Vispa ut mjölet i hälften av mjölken till en slät smet.",
                    "Vispa ner resten av mjölken, äggen och saltet.",
                    "Låt smeten vila cirka 10 minuter.",
                    "Stek tunna pannkakor i lite smör på medelvärme.",
                ),
                tags = listOf("barnvänligt", "snabbt", "frukost"),
            ),
            FamilyRecipe(
                id = "kottfarssas",
                title = "Köttfärssås",
                category = "Middag",
                description = "Mustig vardagsfavorit som passar perfekt till pasta.",
                servings = 4,
                timeMinutes = 35,
                ingredients = listOf(
                    RecipeIngredient("500 g", "nötfärs"),
                    RecipeIngredient("1", "gul lök"),
                    RecipeIngredient("2", "vitlöksklyftor"),
                    RecipeIngredient("400 g", "krossade tomater"),
                    RecipeIngredient("2 msk", "tomatpuré"),
                    RecipeIngredient("1 tsk", "oregano"),
                    RecipeIngredient("1 tsk", "basilika"),
                    RecipeIngredient("1 msk", "olja"),
                    RecipeIngredient("efter smak", "salt och svartpeppar"),
                ),
                steps = listOf(
                    "Finhacka lök och vitlök.",
                    "Bryn färsen i olja tills den fått färg.",
                    "Tillsätt lök och vitlök och stek ytterligare några minuter.",
                    "Rör ner tomatpuré, krossade tomater och kryddor.",
                    "Låt sjuda 15–20 minuter och smaka av med salt och peppar.",
                ),
                tags = listOf("pasta", "familj", "vardag"),
            ),
            FamilyRecipe(
                id = "lasagne",
                title = "Lasagne",
                category = "Middag",
                description = "Krämig familjelasagne med köttfärssås och ostsås.",
                servings = 6,
                timeMinutes = 70,
                ingredients = listOf(
                    RecipeIngredient("500 g", "nötfärs"),
                    RecipeIngredient("1", "gul lök"),
                    RecipeIngredient("500 g", "krossade tomater"),
                    RecipeIngredient("9–12", "lasagneplattor"),
                    RecipeIngredient("7 dl", "mjölk"),
                    RecipeIngredient("3 msk", "vetemjöl"),
                    RecipeIngredient("3 msk", "smör"),
                    RecipeIngredient("2 dl", "riven ost"),
                    RecipeIngredient("efter smak", "salt och svartpeppar"),
                ),
                steps = listOf(
                    "Gör en köttfärssås av färs, lök och tomater.",
                    "Smält smöret, vispa ner mjölet och tillsätt mjölken lite i taget till en slät sås.",
                    "Rör ner hälften av osten i såsen och smaka av.",
                    "Varva köttfärssås, lasagneplattor och ostsås i en form.",
                    "Toppa med resten av osten och grädda i 200 grader cirka 35 minuter.",
                ),
                tags = listOf("ugn", "familj", "pasta"),
            ),
            FamilyRecipe(
                id = "korv-stroganoff",
                title = "Korv stroganoff",
                category = "Middag",
                description = "Snabb och krämig vardagsmiddag med falukorv.",
                servings = 4,
                timeMinutes = 25,
                ingredients = listOf(
                    RecipeIngredient("500 g", "falukorv"),
                    RecipeIngredient("1", "gul lök"),
                    RecipeIngredient("2 msk", "tomatpuré"),
                    RecipeIngredient("3 dl", "matlagningsgrädde"),
                    RecipeIngredient("1 tsk", "paprikapulver"),
                    RecipeIngredient("1 msk", "olja"),
                    RecipeIngredient("efter smak", "salt och svartpeppar"),
                ),
                steps = listOf(
                    "Strimla korven och hacka löken.",
                    "Stek korv och lök i olja tills de fått lite färg.",
                    "Rör ner tomatpuré och paprikapulver.",
                    "Häll på grädden och låt sjuda cirka 10 minuter.",
                    "Smaka av och servera gärna med ris.",
                ),
                tags = listOf("snabbt", "barnvänligt", "ris"),
            ),
            FamilyRecipe(
                id = "kycklinggryta",
                title = "Krämig kycklinggryta",
                category = "Middag",
                description = "Mild kycklinggryta med paprika, vitlök och grädde.",
                servings = 4,
                timeMinutes = 35,
                ingredients = listOf(
                    RecipeIngredient("600 g", "kycklingfilé"),
                    RecipeIngredient("1", "gul lök"),
                    RecipeIngredient("1", "röd paprika"),
                    RecipeIngredient("2", "vitlöksklyftor"),
                    RecipeIngredient("3 dl", "matlagningsgrädde"),
                    RecipeIngredient("1 msk", "kycklingfond"),
                    RecipeIngredient("1 tsk", "paprikapulver"),
                    RecipeIngredient("1 msk", "olja"),
                ),
                steps = listOf(
                    "Skär kycklingen i bitar och bryn den i olja.",
                    "Tillsätt hackad lök, paprika och vitlök.",
                    "Häll på grädde och fond och krydda med paprikapulver.",
                    "Låt sjuda tills kycklingen är genomstekt och såsen tjocknat lätt.",
                ),
                tags = listOf("kyckling", "ris", "familj"),
            ),
            FamilyRecipe(
                id = "ugnsbakad-lax",
                title = "Ugnsbakad lax",
                category = "Middag",
                description = "Enkel lax i ugn med citron och dill.",
                servings = 4,
                timeMinutes = 30,
                ingredients = listOf(
                    RecipeIngredient("600 g", "laxfilé"),
                    RecipeIngredient("1", "citron"),
                    RecipeIngredient("2 msk", "olivolja"),
                    RecipeIngredient("2 msk", "hackad dill"),
                    RecipeIngredient("efter smak", "salt och svartpeppar"),
                ),
                steps = listOf(
                    "Lägg laxen i en ugnsform.",
                    "Ringla över olja och pressa över citron.",
                    "Krydda med dill, salt och peppar.",
                    "Tillaga i 200 grader cirka 18–22 minuter beroende på tjocklek.",
                ),
                tags = listOf("fisk", "ugn", "snabbt"),
            ),
            FamilyRecipe(
                id = "spaghetti-carbonara",
                title = "Spaghetti carbonara",
                category = "Middag",
                description = "Krämig pasta med bacon, ägg och parmesan.",
                servings = 4,
                timeMinutes = 25,
                ingredients = listOf(
                    RecipeIngredient("400 g", "spaghetti"),
                    RecipeIngredient("200 g", "bacon"),
                    RecipeIngredient("3", "ägg"),
                    RecipeIngredient("1,5 dl", "finriven parmesan"),
                    RecipeIngredient("1 tsk", "svartpeppar"),
                    RecipeIngredient("1 nypa", "salt"),
                ),
                steps = listOf(
                    "Koka pastan enligt anvisningen och spara lite pastavatten.",
                    "Stek bacon knaprigt.",
                    "Vispa ihop ägg, parmesan och svartpeppar.",
                    "Vänd ner varm pasta och bacon i äggblandningen utanför direkt värme.",
                    "Späd med lite pastavatten tills såsen blir blank och krämig.",
                ),
                tags = listOf("pasta", "snabbt"),
            ),
            FamilyRecipe(
                id = "tacos",
                title = "Fredagstacos",
                category = "Middag",
                description = "Klassiska familjetacos med färs och valfria tillbehör.",
                servings = 4,
                timeMinutes = 25,
                ingredients = listOf(
                    RecipeIngredient("500 g", "nötfärs"),
                    RecipeIngredient("1 påse", "tacokrydda"),
                    RecipeIngredient("8", "tortillabröd"),
                    RecipeIngredient("1", "salladshuvud"),
                    RecipeIngredient("2", "tomater"),
                    RecipeIngredient("1", "gurka"),
                    RecipeIngredient("2 dl", "riven ost"),
                    RecipeIngredient("2 dl", "gräddfil"),
                    RecipeIngredient("1 burk", "tacosås"),
                ),
                steps = listOf(
                    "Bryn färsen och tillsätt tacokrydda enligt smak.",
                    "Hacka grönsakerna och lägg tillbehören i skålar.",
                    "Värm tortillabröden.",
                    "Låt alla fylla sina egna tacos.",
                ),
                tags = listOf("fredag", "barnvänligt", "snabbt"),
            ),
            FamilyRecipe(
                id = "kottbullar",
                title = "Köttbullar",
                category = "Middag",
                description = "Saftiga köttbullar med klassisk mild kryddning.",
                servings = 4,
                timeMinutes = 40,
                ingredients = listOf(
                    RecipeIngredient("500 g", "blandfärs"),
                    RecipeIngredient("1", "gul lök"),
                    RecipeIngredient("1 dl", "ströbröd"),
                    RecipeIngredient("1,5 dl", "mjölk"),
                    RecipeIngredient("1", "ägg"),
                    RecipeIngredient("1 tsk", "salt"),
                    RecipeIngredient("0,5 tsk", "svartpeppar"),
                    RecipeIngredient("2 msk", "smör"),
                ),
                steps = listOf(
                    "Blanda ströbröd och mjölk och låt svälla i 5 minuter.",
                    "Finhacka löken och blanda med färs, ägg och kryddor.",
                    "Forma små köttbullar.",
                    "Stek i smör på medelvärme tills de är genomstekta.",
                ),
                tags = listOf("husmanskost", "familj"),
            ),
            FamilyRecipe(
                id = "chili-sin-carne",
                title = "Chili sin carne",
                category = "Vegetariskt",
                description = "Mustig vegetarisk chili med bönor, majs och tomat.",
                servings = 4,
                timeMinutes = 35,
                ingredients = listOf(
                    RecipeIngredient("1", "gul lök"),
                    RecipeIngredient("2", "vitlöksklyftor"),
                    RecipeIngredient("400 g", "krossade tomater"),
                    RecipeIngredient("1 burk", "kidneybönor"),
                    RecipeIngredient("1 burk", "svarta bönor"),
                    RecipeIngredient("1 liten burk", "majs"),
                    RecipeIngredient("1 tsk", "spiskummin"),
                    RecipeIngredient("1 tsk", "paprikapulver"),
                    RecipeIngredient("0,5 tsk", "chilipulver"),
                ),
                steps = listOf(
                    "Fräs hackad lök och vitlök i lite olja.",
                    "Tillsätt kryddorna och låt dem fräsa med kort.",
                    "Häll i tomater, sköljda bönor och majs.",
                    "Låt sjuda cirka 20 minuter och smaka av.",
                ),
                tags = listOf("vegetariskt", "bönor", "vardag"),
            ),
            FamilyRecipe(
                id = "tomatsoppa",
                title = "Krämig tomatsoppa",
                category = "Soppa",
                description = "Len tomatsoppa som passar både lunch och enkel middag.",
                servings = 4,
                timeMinutes = 30,
                ingredients = listOf(
                    RecipeIngredient("800 g", "krossade tomater"),
                    RecipeIngredient("1", "gul lök"),
                    RecipeIngredient("2", "vitlöksklyftor"),
                    RecipeIngredient("3 dl", "grönsaksbuljong"),
                    RecipeIngredient("1 dl", "matlagningsgrädde"),
                    RecipeIngredient("1 tsk", "basilika"),
                ),
                steps = listOf(
                    "Fräs hackad lök och vitlök mjuka.",
                    "Tillsätt tomater, buljong och basilika.",
                    "Låt sjuda cirka 15 minuter.",
                    "Mixa soppan slät och rör ner grädden.",
                ),
                tags = listOf("soppa", "vegetariskt", "snabbt"),
            ),
            FamilyRecipe(
                id = "kladdkaka",
                title = "Kladdkaka",
                category = "Bakning",
                description = "Klassisk chokladig kladdkaka med mjuk mitt.",
                servings = 8,
                timeMinutes = 30,
                ingredients = listOf(
                    RecipeIngredient("100 g", "smör"),
                    RecipeIngredient("2,5 dl", "strösocker"),
                    RecipeIngredient("2", "ägg"),
                    RecipeIngredient("1,5 dl", "vetemjöl"),
                    RecipeIngredient("4 msk", "kakao"),
                    RecipeIngredient("1 tsk", "vaniljsocker"),
                    RecipeIngredient("1 nypa", "salt"),
                ),
                steps = listOf(
                    "Sätt ugnen på 175 grader och smörj en form.",
                    "Smält smöret.",
                    "Rör ihop socker och ägg utan att vispa luftigt.",
                    "Rör ner smör och torra ingredienser.",
                    "Grädda 14–18 minuter beroende på hur kladdig du vill ha den.",
                ),
                tags = listOf("choklad", "fika", "bakning"),
            ),
            FamilyRecipe(
                id = "kanelbullar",
                title = "Kanelbullar",
                category = "Bakning",
                description = "Mjuka bullar med smörig kanelfyllning.",
                servings = 20,
                timeMinutes = 120,
                ingredients = listOf(
                    RecipeIngredient("25 g", "jäst"),
                    RecipeIngredient("5 dl", "mjölk"),
                    RecipeIngredient("150 g", "smör"),
                    RecipeIngredient("1 dl", "strösocker"),
                    RecipeIngredient("0,5 tsk", "salt"),
                    RecipeIngredient("13–14 dl", "vetemjöl"),
                    RecipeIngredient("100 g", "smör till fyllning"),
                    RecipeIngredient("1 dl", "strösocker till fyllning"),
                    RecipeIngredient("2 msk", "kanel"),
                    RecipeIngredient("1", "ägg till pensling"),
                ),
                steps = listOf(
                    "Smula jästen i en bunke och lös den i fingervarm mjölk.",
                    "Tillsätt smält smör, socker, salt och nästan allt mjöl.",
                    "Arbeta degen smidig och låt jäsa cirka 40 minuter.",
                    "Kavla ut, bred på smör och strö över socker och kanel.",
                    "Rulla ihop, skär bullar och låt jäsa ytterligare cirka 30 minuter.",
                    "Pensla med ägg och grädda i 225 grader cirka 8–10 minuter.",
                ),
                tags = listOf("fika", "bullar", "bakning"),
            ),
            FamilyRecipe(
                id = "chokladbollar",
                title = "Chokladbollar",
                category = "Bakning",
                description = "Snabba chokladbollar utan ugn.",
                servings = 20,
                timeMinutes = 20,
                ingredients = listOf(
                    RecipeIngredient("100 g", "smör"),
                    RecipeIngredient("1 dl", "strösocker"),
                    RecipeIngredient("3 dl", "havregryn"),
                    RecipeIngredient("3 msk", "kakao"),
                    RecipeIngredient("1 tsk", "vaniljsocker"),
                    RecipeIngredient("2 msk", "kallt kaffe"),
                    RecipeIngredient("1 dl", "kokos eller pärlsocker"),
                ),
                steps = listOf(
                    "Blanda smör och socker.",
                    "Rör ner havregryn, kakao, vaniljsocker och kaffe.",
                    "Forma små bollar.",
                    "Rulla i kokos eller pärlsocker och kyl före servering.",
                ),
                tags = listOf("fika", "snabbt", "utan ugn"),
            ),
            FamilyRecipe(
                id = "bananpannkakor",
                title = "Bananpannkakor",
                category = "Frukost & enkelt",
                description = "Enkla små pannkakor med banan och ägg.",
                servings = 2,
                timeMinutes = 15,
                ingredients = listOf(
                    RecipeIngredient("2", "mogna bananer"),
                    RecipeIngredient("4", "ägg"),
                    RecipeIngredient("1 tsk", "kanel"),
                    RecipeIngredient("1 msk", "smör"),
                ),
                steps = listOf(
                    "Mosa bananerna fint.",
                    "Vispa ihop med ägg och kanel.",
                    "Stek små pannkakor i smör på medelvärme.",
                ),
                tags = listOf("frukost", "snabbt"),
            ),
            FamilyRecipe(
                id = "ugnspannkaka",
                title = "Ugnspannkaka",
                category = "Middag",
                description = "En enkel familjerätt som sköter sig själv i ugnen.",
                servings = 4,
                timeMinutes = 40,
                ingredients = listOf(
                    RecipeIngredient("4", "ägg"),
                    RecipeIngredient("8 dl", "mjölk"),
                    RecipeIngredient("4 dl", "vetemjöl"),
                    RecipeIngredient("0,5 tsk", "salt"),
                    RecipeIngredient("25 g", "smör"),
                ),
                steps = listOf(
                    "Sätt ugnen på 225 grader.",
                    "Vispa ihop ägg, hälften av mjölken, mjöl och salt till en slät smet.",
                    "Vispa ner resten av mjölken.",
                    "Smält smöret i en långpanna och häll i smeten.",
                    "Grädda cirka 25–30 minuter.",
                ),
                tags = listOf("barnvänligt", "ugn", "enkelt"),
            ),
            FamilyRecipe(
                id = "kycklingpasta",
                title = "Krämig kycklingpasta",
                category = "Middag",
                description = "Snabb pasta med kyckling, vitlök och parmesan.",
                servings = 4,
                timeMinutes = 30,
                ingredients = listOf(
                    RecipeIngredient("400 g", "pasta"),
                    RecipeIngredient("500 g", "kycklingfilé"),
                    RecipeIngredient("2", "vitlöksklyftor"),
                    RecipeIngredient("3 dl", "matlagningsgrädde"),
                    RecipeIngredient("1 dl", "riven parmesan"),
                    RecipeIngredient("1 msk", "olja"),
                    RecipeIngredient("efter smak", "salt och svartpeppar"),
                ),
                steps = listOf(
                    "Koka pastan enligt anvisningen.",
                    "Skär kycklingen i bitar och bryn den i olja.",
                    "Tillsätt vitlök och grädde och låt sjuda tills kycklingen är klar.",
                    "Rör ner parmesan och vänd ihop med pastan.",
                ),
                tags = listOf("pasta", "kyckling", "snabbt"),
            ),
            FamilyRecipe(
                id = "fiskgratäng",
                title = "Enkel fiskgratäng",
                category = "Middag",
                description = "Mild fiskgratäng med potatismos och dillsås.",
                servings = 4,
                timeMinutes = 50,
                ingredients = listOf(
                    RecipeIngredient("600 g", "vit fiskfilé"),
                    RecipeIngredient("800 g", "potatis"),
                    RecipeIngredient("2 dl", "mjölk"),
                    RecipeIngredient("25 g", "smör"),
                    RecipeIngredient("2,5 dl", "matlagningsgrädde"),
                    RecipeIngredient("2 msk", "dill"),
                    RecipeIngredient("1 tsk", "citronjuice"),
                ),
                steps = listOf(
                    "Koka potatisen mjuk och gör mos med mjölk och smör.",
                    "Lägg fisken i mitten av en ugnsform och spritsa eller klicka mos runtom.",
                    "Blanda grädde, dill och citron och häll över fisken.",
                    "Grädda i 200 grader cirka 20–25 minuter tills fisken är klar.",
                ),
                tags = listOf("fisk", "ugn", "familj"),
            ),
            FamilyRecipe(
                id = "hamburgare",
                title = "Hemgjorda hamburgare",
                category = "Middag",
                description = "Saftiga burgare med enkla klassiska tillbehör.",
                servings = 4,
                timeMinutes = 30,
                ingredients = listOf(
                    RecipeIngredient("600 g", "nötfärs"),
                    RecipeIngredient("4", "hamburgerbröd"),
                    RecipeIngredient("4 skivor", "ost"),
                    RecipeIngredient("1", "tomat"),
                    RecipeIngredient("1", "gul lök"),
                    RecipeIngredient("4 blad", "sallad"),
                    RecipeIngredient("efter smak", "salt och svartpeppar"),
                ),
                steps = listOf(
                    "Forma fyra burgare utan att arbeta färsen för mycket.",
                    "Salta och peppra strax före stekning.",
                    "Stek eller grilla till önskad stekgrad och lägg på ost mot slutet.",
                    "Servera i bröd med valfria tillbehör.",
                ),
                tags = listOf("helg", "grill", "familj"),
            ),
            FamilyRecipe(
                id = "overnight-oats",
                title = "Overnight oats",
                category = "Frukost & enkelt",
                description = "Förbered frukosten kvällen innan.",
                servings = 1,
                timeMinutes = 5,
                ingredients = listOf(
                    RecipeIngredient("1 dl", "havregryn"),
                    RecipeIngredient("1 dl", "mjölk"),
                    RecipeIngredient("1 dl", "yoghurt"),
                    RecipeIngredient("1 tsk", "honung"),
                    RecipeIngredient("0,5 dl", "bär"),
                ),
                steps = listOf(
                    "Blanda havregryn, mjölk, yoghurt och honung i en burk.",
                    "Ställ i kyl över natten.",
                    "Toppa med bär före servering.",
                ),
                tags = listOf("frukost", "förbereda", "snabbt"),
            ),
        )

    fun search(query: String): List<FamilyRecipe> {
        val normalized = query.trim().lowercase(Locale("sv", "SE"))
        if (normalized.isBlank()) return all

        val terms = normalized.split(Regex("\\s+")).filter { it.isNotBlank() }
        return all
            .map { recipe ->
                val searchable =
                    buildString {
                        append(recipe.title)
                        append(' ')
                        append(recipe.category)
                        append(' ')
                        append(recipe.description)
                        append(' ')
                        append(recipe.tags.joinToString(" "))
                        append(' ')
                        append(recipe.ingredients.joinToString(" ") { it.name })
                    }.lowercase(Locale("sv", "SE"))
                recipe to terms.count { it in searchable }
            }
            .filter { (_, score) -> score > 0 }
            .sortedWith(
                compareByDescending<Pair<FamilyRecipe, Int>> { it.second }
                    .thenBy { it.first.timeMinutes }
                    .thenBy { it.first.title }
            )
            .map { it.first }
    }
}
